### ISSUE TITLE
Need polished genome?

### ISSUE THREAD

**Issue by yplee614** [phasegenomics/FALCON-Phase#10]
The falcon-phase input the falcon-unzip results, it not corrected by pacbio reads or Illumina reads, it need to be polished before running the FALCON-Phase?

**Comment by skingan** [comment]
You should use the final output from FALCON-Unzip: `cns_p_ctg.fa` and `cns_h_ctg.fa` which has had one round of polishing with the PacBio reads. It is not necessary to polish with illumina data prior to running FALCON-Phase.
