### ISSUE TITLE
Type in README.md

### ISSUE THREAD

**Issue by aboyher** [phasegenomics/FALCON-Phase#13]
Minor issue, there's a type in the README.md. In describing the output files, section "Emission of Phased Haplotigs (Workflow Step 6), you list "phase0.bed" twice instead of "phase1.bed" (I assume).

https://github.com/phasegenomics/FALCON-Phase#emission-of-phased-haplotigs-workflow-step-6

**Comment by skingan** [comment]
Thank you for noticing this.

**Comment by skingan** [comment]
fixed.
