### ISSUE TITLE
Test data set results

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [phasegenomics/FALCON-Phase#15]
Thanks for getting this HiC integration for phased assemblies going. It was pretty straight forward to set up. I just finished the test run, both on the cluster and local, and all behaved fine. The only warnings I got are 
Warning: error in phasing 000000F_001:0-26421 and 000000F:10327801-10353990 'phased.txt' contains '-nan' .

Is this anything concerning? 

Also do you you have md5sums or such for the output of the test_data?

**Comment by zeeev** [comment]
Hi @BenjaminSchwessinger 

Thanks for the feedback. The reason you're seeing NANs is that the number of permutations is low in the test config.json. Increasing the number to greater than 10Million should remove the warning. The test set was only put in place to make sure the pipeline ran. The results of the test set is meaningless. In the future we should use a test dataset where the phase is validated.
