### ISSUE TITLE
Understanding the output of FALCON-Phase

### ISSUE THREAD

**Issue by bgbrink** [phasegenomics/FALCON-Phase#22]
Thanks a lot for developing this complex algorithm. I hope you can help me out so close to the finish line. I have troubles understanding the output files of the FALCON-Phase assembly. In the `readme.md` you say it should look like this: 
```
    job_dir/
    ├── output/
            ├── test_data.phased.0.bed/    # list of minced contigs used to reconstruct phase 0 output
            ├── test_data.phased.1.bed/    # list of minced contigs used to reconstruct phase 1 output
            ├── test_data.phased.0.fasta/   # phase 0 output
            ├── test_data.phased.1.fasta/   # phase 1 output
```
However, this is not the case for me, so I checked if the pipeline did not finish. This does not seem to be the case, here is the end of the log file.
```
Finished job 3.
263 of 265 steps (99%) done
Resources before job selection: {'_cores': 1, '_nodes': 9223372036854775807}
Ready jobs (1):
	emit_haplotigs
Selected jobs (1):
	emit_haplotigs
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775806}

Job 1: [info] emitting phased haplotigs


            /work/project/ladsie_002/FALCON-Phase/bin/emit_haplotigs.pl falcon-assembly-funghi.phased.txt mince/falcon-assembly-funghi.BC.bed falcon-assembly-funghi.p_h_ctg.fa /opt/software/ngs/bedtools-2.26.0/bin/bedtools > falcon-assembly-funghi.diploid_phased.fasta

            rm tmp_phase1.txt
            rm tmp_phase0.txt
     
Releasing 1 _cores (now 1).
Releasing 1 _nodes (now 9223372036854775807).
Finished job 1.
264 of 265 steps (100%) done
Resources before job selection: {'_cores': 1, '_nodes': 9223372036854775807}
Ready jobs (1):
	dummy
Selected jobs (1):
	dummy
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775806}

localrule dummy:
    input: falcon-assembly-funghi.diploid_phased.fasta
    jobid: 0

Releasing 1 _cores (now 1).
Releasing 1 _nodes (now 9223372036854775807).
Finished job 0.
265 of 265 steps (100%) done
Complete log: /work/project/ladsie_002/FALCON-Phase/pipeline/.snakemake/log/2018-07-02T114157.539276.snakemake.log
unlocking
removing lock
removing lock
removed all locks
```
I have the following structure instead. Maybe the `readme.md` is outdated?
```
    job_dir/
    ├── coord_files/
    ├── delta_files/
    ├── filtered_delta_files/
    ├── haplotig_placement_file/
    ├── mince/
    ├── falcon-assembly-funghi.binmat
    ├── falcon-assembly-funghi.diploid_phased.fasta
    ├── falcon-assembly-funghi.filtered.bam
    ├── falcon-assembly-funghi.ov_index.txt
    ├── falcon-assembly-funghi.phased.txt
    ├── falcon-assembly-funghi.p_h_ctg.fa
    ├── falcon-assembly-funghi.p_h_ctg.fa.fai
    ├── falcon-assembly-funghi.unfiltered.bam
    ├── phase0.bed
    ├── phase1.bed
```
I assume that `falcon-assembly-funghi.diploid_phased.fasta`is the final result. These are the first 10 sequence headers:
```
>000000F::000000F:0-5824_0
>000000F::000000F_013:0-17222_0
>000000F::000000F:23088-37691_0
>000000F::000000F:37691-68686_0
>000000F::000000F:68686-312436_0
>000000F::000000F_014:0-80655_0
>000000F::000000F_030:0-193921_0
>000000F::000000F:551499-576539_0
>000000F::000000F_034:0-519081_0
>000000F::000000F:1082880-1458819_0
```
What does this mean? These are supposed to be on the same phase, signalized by the _0. Shouldn't FALCON-Phase emit two phased full-length pseudo-haplotypes for each primary contig? 
The first sequence is 0-5824 from contig 000000F and the second sequence is 0-17222 from 000000F_013? Can I just concatenate them? Why are 3 and 4 separate entries, even though they appear to be continuous sequences?

**Comment by skingan** [comment]
Hello,

It appears that you are using an older version of the code. We updated the directory structure and added an additional output format option last week:

https://github.com/phasegenomics/FALCON-Phase/commit/c86f05e1f45e0db2496834bd7ba9c7905a242aae

You will need to pull and compile the new code, modify your config file (there is a new [output_format](https://github.com/phasegenomics/FALCON-Phase#sample-setup-link) option), and delete these files:

    ├── falcon-assembly-funghi.binmat
    ├── falcon-assembly-funghi.diploid_phased.fasta
    ├── falcon-assembly-funghi.filtered.bam
    ├── falcon-assembly-funghi.ov_index.txt
    ├── falcon-assembly-funghi.phased.txt
    ├── falcon-assembly-funghi.p_h_ctg.fa
    ├── falcon-assembly-funghi.p_h_ctg.fa.fai
    ├── falcon-assembly-funghi.unfiltered.bam
    ├── phase0.bed
    ├── phase1.bed

And then relaunch the run. I apologize for this inconvenience.

Hopefully this will clean up the strange headers that you have in your output fasta file. If not, please let us know. Be sure you have the correct [bedtools](https://github.com/phasegenomics/FALCON-Phase#dependencies-rage2) version.

Thanks,
Sarah

**Comment by bgbrink** [comment]
Thank you for the swift response. I was indeed running an older version of the code and now I obtain the correct directory sturcture. However, I am still wondering about the sequence headers in the fasta file. For `output_format=pseudohap`, it looks just like before:
```
>000000F::000000F:0-5824_0
>000000F::000000F_013:0-17222_0
>000000F::000000F:23088-37691_0
>000000F::000000F:37691-68686_0
>000000F::000000F:68686-312436_0
>000000F::000000F_014:0-80655_0
>000000F::000000F_030:0-193921_0
>000000F::000000F:551499-576539_0
>000000F::000000F_034:0-519081_0
>000000F::000000F:1082880-1458819_0
```
For `output_format=unzip`, it looks like this:
```
>000000F::000000F:0-5824
>000000F::000000F:5824-23088
>000000F::000000F:23088-37691
>000000F::000000F_009:0-31035
>000000F::000000F:68686-312436
>000000F::000000F:312436-393019
>000000F::000000F:358482-551499
>000000F::000000F:551499-576539
>000000F::000000F:576539-1082880
>000000F::000000F:1082880-1458819
```
Could you please elaborate a little bit how to interpret this data, e.g. what the first and second contig name refer to and especially the numbers. Are these haplotig blocks? What does it mean if there are overlapping numbers or gaps? 

Furthermore, I noticed that the fasta files contain lower case bases, do they refer to repetitive regions?

**Comment by skingan** [comment]
Hi Benedikt,

This is a bug, the headers are not supposed to look like that. For the "0" output, the fragments should be concatenated together into a single sequence with header "000000F_0".

Could you share with me the following files:

1. falcon-assembly-funghi.phased.txt
2. mince/falcon-assembly-funghi.BC.bed
3. falcon-assembly-funghi.p_h_ctg.fa

so I can trouble shoot? The last file will be deleted in the pipeline but can be recreated by
concatenating your p and h fasta files together.

Thank you,
Sarah

**Comment by skingan** [comment]
Regarding lowercase bases, these fasta files have been polished once as part of "fc_quiver" in the falcon unzip stage of assembly. In polishing, regions of the reference with poor raw read support (less than 5X coverage in a ~500bp window) and output as lowercase. Lowercase indicates that a new consensus sequence was not generated but rather, the reference bases were output.

Also, FYI, the ID before the "::" is the desired header. The coordinates after the "::" indicate the fragments from the original FALCON-Unzip assembly that are being concatenated together into the phased sequence. The fragments are also listed in the BED file in order.

**Comment by bgbrink** [comment]
Hi Sarah,
thanks for the explainations, I was guessing something like this. In conclusion - as a temporary workaround - it makes perfect sense to concatenate all sequences that start with `000000F::`, all sequences that start with `000002F::`, etc, correct?

The sequencing data is unpublished, so I would rather not disclose it openly here. Is there any way I can contact you directly?

**Comment by skingan** [comment]
Hi Benedikt,

I understand. You can e-mail to skingan@pacificbiosciences.com or share google or dropbox files with sarahdoom@gmail.com.

In the meantime, if you are interested in the pseudohaplotype [output](https://github.com/phasegenomics/FALCON-Phase#emission-of-phased-haplotigs-workflow-step-6) (for example if you want to scaffold a diploid assembly), you can concatenate all seqs with the same header prefix within the 0 and 1 output files.

Sarah

**Comment by skingan** [comment]
After receiving the requested files, I was unable to reproduce the bug with the suggested bedtools version (2.27.1).
