### ISSUE TITLE
Test coverage (dataset)

### ISSUE THREAD

**Issue by zeeev** [phasegenomics/FALCON-Phase#23]
Making changes to the FALCON-Phase binary code should be benchmarked against a known dataset that is fast to run. I'm concerned that changes to the data structures or small changes to the algorithm could silently bias the results. To resolve this we need the following:

TODO:
-[ ] a small biological dataset where truth is know (FASTA, binmat, overlap file)
-[ ] a function to score the output of the algorithm
-[ ] add ```make test```
-[ ] add ```make test``` to ```travis.yaml```

**Comment by skingan** [comment]
I will generate a parent-assignment dataset that can be compared to phase assignment. I will also update the scoring script used with the Bull dataset for easy testing.

**Comment by skingan** [comment]
TODO:
-[X] a small biological dataset where truth is know (FASTA, binmat, overlap file)
-[X] a function to score the output of the algorithm
-[ ] add make test
-[ ] add make test to travis.yaml
