### ISSUE TITLE
cat command returns "Argument list too long"

### ISSUE THREAD

**Issue by pwmcclurg** [phasegenomics/FALCON-Phase#25]
I have successfully installed FALCON-phase and am currently running the snakefile on blueberry (~800mb) with the following command:

snakemake -s snakefile --verbose -p 

I have 3689 .coords file that are being set to the cat command and I receive the dreaded "Argument list too long".  I was hoping someone may have encountered this problem and found a workaround.  I set 

ulimit -n 10000

but to no avail

The error occurs duringhis is during the section:

Job 12: [info] making haplotig placement file

whcih I'm assuming is according to this rule (line 179 in sndakefile)

rule placement   :
     message     : "[info] making haplotig placement file"
     input       : CO=expand("coords_files/{{sample}}.{primary}.coords", primary=PRIMARY.keys()), HP=config['hp'], ST=config['samtools']
     output      : "coords_files/{sample}.coords.out", "haplotig_placement_file/{sample}.hp.txt"
     shell       : """
               cat {input.CO} | sort -k11,11 -k1,1n  > {output[0]}
               {input.HP} {output[0]} | sort -k6,6 -k8,8n > {output[1]}
               """
The error looks like:

"The cat command of .coords file - which is too long....:)

 /archive/jenkins_test/pmcclurg/FALCON-Phase/bin/coords2hp.py coords_files/blu_mask_data.coords.out | sort -k6,6 -k8,8n > haplotig_placement_file/blu_mask_data.hp.txt

Full Traceback (most recent call last):
  File "/archive/jenkins_test/pmcclurg/miniconda3/lib/python3.6/site-packages/snakemake/executors.py", line 1288, in run_wrapper
    singularity_args, use_singularity, None, jobid, is_shell)
  File "/archive/jenkins_test/pmcclurg/FALCON-Phase/pipeline/snakefile", line 389, in __rule_placement
  File "/archive/jenkins_test/pmcclurg/miniconda3/lib/python3.6/site-packages/snakemake/shell.py", line 111, in __new__
    close_fds=close_fds, **cls._process_args)
  File "/archive/jenkins_test/pmcclurg/miniconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/archive/jenkins_test/pmcclurg/miniconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/usr/bin/bash'

    Error in rule placement:
        jobid: 12
        output: coords_files/blu_mask_data.coords.out, haplotig_placement_file/blu_mask_data.hp.txt

**Comment by skingan** [comment]
Hello pwmcclurg,

Thank you for bringing this to our attention and for the helpful error messages. I can fix this bug but it may take a few days for the new code to be available.

In the mean time, you can manually run the commands in that snakemake rule and then restart the pipeline. It should see that the files are there and move on to the next rule.

Something like:

find coords_files/ -name "*.coords" | xargs -I {} cat {} >> coords.list
sort coords.list -k11,11 -k1,1n > {output[0]}
{input.HP} {output[0]} | sort -k6,6 -k8,8n > {output[1]}

Obviously, you'll need to substitute the names in curly brackets with the actual file name or executable.

Let us know if this resolves the issue.

Best,
-Sarah

**Comment by skingan** [comment]
Note to Sarah: rewrite placement_file rule to use find and xargs rather than a wicked long cat list.

**Comment by pwmcclurg** [comment]
Thank you Sarah - and thank you for the bypass commands - I was about to assemble all this from stack exchange but how nice to receive some corroboration - that's great how all these pipelines can recover so nicely.  I had tried ulimit -s to increase the system stack size which sometime works for long arguments but to no avail - I will definitely try this to move on.

**Comment by skingan** [comment]
this is a corner case with a clear workaround.
