### ISSUE TITLE
Error in rule placement

### ISSUE THREAD

**Issue by zhidaobuzhidao** [phasegenomics/FALCON-Phase#29]
I have an error in rule placement and cannot find the reason. It is successful for test data.The logs are as below:
Error in rule placement:
    jobid: 12
    output: coords_files/test_data.coords.out, haplotig_placement_file/test_data.hp.txt
    cluster_jobid: Your job 2802530 ("falcon-phase") has been submitted.
I can not get the first output 'file test_data.coords.out'  even all coords files existed.

**Comment by skingan** [comment]
Hello,

Can you find the cluster submission log files so we can see a more detailed error message?

Alternatively, if you try running the placement rule commands by hand, is there an error?

Sarah

**Comment by zeeev** [comment]
Hi @zhidaobuzhidao 

Since we haven't heard from you in a month I'm going to close this issue. However, feel free to create a new issue when you're ready to revisit the issue.
