### ISSUE TITLE
scrub_names.pl throws errors and creates empty output

### ISSUE THREAD

**Issue by ghannum** [phasegenomics/FALCON-Phase#30]
Error example:
> scrub_names.pl 4-quiver/cns-output/cns_p_ctg.fasta 4-quiver/cns-output/cns_h_ctg.fasta > name_mapping.txt
....
Use of uninitialized value $sname[0] in hash element at /tools/FALCON-Phase/bin/scrub_names.pl line 91, <$INB> line 53763.
....

The 'clean' files are generated, but the 'name_mapping.txt' file is empty.

**Comment by ghannum** [comment]
The 'p' contigs file works fine, but it looks like the error is with the 'h' contigs.

The 'h' contigs file has names which look like this: '000000Fp01_00001|arrow'.
The 'clean' script makes all 'h' contig names blank.

**Comment by zeeev** [comment]
Hi @ghannum, 

Are these data private? Could you make a small test case? I'd be happy to trouble shoot the issue. Have the ctg names been modified in any way after assembly?

Best,

Zev

**Comment by ghannum** [comment]
It is private data, and I did not change the ctg names.

That being said, I am running a very recent release of Falcon (7/31/18). Perhaps they changed the contig name format? The example I gave '000000Fp01_00001|arrow' may not match the regex this script expects.

**Comment by skingan** [comment]
That's exactly right, the contig ID nomenclature has changed with the new version of FALCON.

**Comment by skingan** [comment]
ghannum, please pull a new copy of the repo and you will find a perl script, [FALCON_headerConverter.pl](https://github.com/phasegenomics/FALCON-Phase/blob/master/bin/FALCON_headerConverter.pl) that you can run on your primary and haplotig fasta files. It will convert your fasta headers to a compatible format for FALCON-Phase. You will still need to run scrub_names.pl from the new files.
