### ISSUE TITLE
FALCON-Phase does not emit primary contigs without a haplotig

### ISSUE THREAD

**Issue by abardill** [phasegenomics/FALCON-Phase#31]
The final assemblies produced by FALCON-Phase exclude primary contigs which have no aligned haplotigs. This appears to be the case whether or not I output pseudohaplotypes or primary contigs and haplotigs. Is this intentional?

**Comment by zeeev** [comment]
Hi @abardill,

This is indeed not the desired behavior. @skingan might have a better sense of the problem. 

What to the contig names look like? What version of FALCON did you use?

**Comment by skingan** [comment]
This is expected based on the designed workflow but isn't ideal behavior and can be fixed.

To Do: In final emission, use full list of contigs to generate fasta files rather than just contigs that have entries in the haplotig placement file.

**Comment by skingan** [comment]
@abardill I'm actually not seeing this behavior, my earlier comment was wrong. The emission script [emit_haplotigs.pl](https://github.com/phasegenomics/FALCON-Phase/blob/master/bin/emit_haplotigs.pl) uses the `BC.bed` file to traverse the contigs which contains all primary contigs, even those without haplotigs.
