### ISSUE TITLE
Multiple restriction motifs?

### ISSUE THREAD

**Issue by Adamtaranto** [phasegenomics/FALCON-Phase#38]
Is it possible to pass more than one restriction enzyme motif to falcon-phase? i.e. For libraries produced with the Phase Genomics Microbe Hi-C kit.

**Comment by zeeev** [comment]
Hi @Adamtaranto,

We've added the ability to use multiple restriction enzymes. The feature lives on the development branch until we finalize our testing. For further details see: https://github.com/phasegenomics/FALCON-Phase/issues/9

Best,

Zev
