### ISSUE TITLE
makefile bug    -lcurl 

### ISSUE THREAD

**Issue by hewm2008** [phasegenomics/FALCON-Phase#42]
you should add the  lib [-lcurl]  in the makefile [src/Makefile]  lines  17

-lbz2 -llzma -lz -lm -lpthread    

===>

-lbz2 -llzma -lz -lm  -lcurl   -lpthread

**Comment by zeeev** [comment]
Hi @hewm2008,

Can you elaborate? Was there a build error? Is lib curl required by htslib? We've built this code across several operating systems without issue, that doesn't mean there is not a problem  :-).

Best,

Zev
