### ISSUE TITLE
how to edit the config.sh

### ISSUE THREAD

**Issue by xiaoaozqd** [phasegenomics/FALCON-Phase#47]
when I run the pipline with test data locally with the code "snakemake -s snakefile --verbose -p" 
there are  warning or error in the stdout, I'm not sure how to fix it, should I install the module in python 3.6?:
config.sh:line1: module: Command not found
config.sh:line2: module: Command not found
config.sh:line3: module: Command not found
config.sh:line4: module: Command not found
config.sh:line5: module: Command not found

If I run snakemake on a cluster, how to edit this file?

**Comment by skingan** [comment]
Does the test run complete despite the errors?
