### ISSUE TITLE
Fix falcon-phase printing order bug 

### ISSUE THREAD

**Issue by zeeev** [phasegenomics/FALCON-Phase#56]
The falcon-phase binary has a silly printing error where it looks like:

falcon-phase -I my.bam -o my.filt.bam filter.

**Comment by pb-cdunn** [comment]
Could you clarify the bug? I don't see one in our version. I see this:
```
./alignment-filter/template.sh:falcon-phase bamfilt -f 20 -m 10 -i {input.bam_unfiltered} -o {output.bam_filtered}
./alignment-filter/user_script.sh:falcon-phase bamfilt -f 20 -m 10 -i ../alignment/aln.unfiltered.bam -o aln.filtered.bam
```
That looks fine to me. I don't see where something would be printed for execution from the C code.

**Comment by zeeev** [comment]
Hi Chris,

Thanks for asking about this bug. Below are the details. I'll likely have the time to address this low-priority issue soon.

Here's the block that prints the code:

https://github.com/phasegenomics/FALCON-Phase/blob/0be7fbe79a040e9d89243298bd079da891486528/src/bam_filt.c#L294

Here's the initial report of a wonky print:

https://github.com/phasegenomics/FALCON-Phase/issues/55#issuecomment-446757847

**Comment by shawnpg** [comment]
Closing as we haven't had other reports of this being an issue since the original discussion.
