### ISSUE TITLE
Can we concat haplotypes.fasta and haplotigs.fasta sequences ?

### ISSUE THREAD

**Issue by jnarayan81** [phasegenomics/FALCON-Phase#61]
Is this alright to concat collapsed and phase fasta sequence to create a pseudo haploid genome ? 

```
cat test.A_haplotigs.fasta  test.collapsed_haplotypes.fasta > Haploid_A.fa
cat test.B_haplotigs.fasta  test.collapsed_haplotypes.fasta > Haploid_B.fa
```

Note: These files are created at mincing stage of Falcon-Phase

**Comment by skingan** [comment]
The contigs will be highly fragmented, but all the material for a pseudohaploid genome is contained in those files.
