### ISSUE TITLE
run with nanopore data

### ISSUE THREAD

**Issue by yilunhuangyue** [phasegenomics/FALCON-Phase#62]
Hi, I am wondering if FALCON-Phase could be used fo nanopore data? Or can we convert the header of nanopore  to pacbio in order to fit FALCON/Falcon-phase? 
Thanks for any advices.

**Comment by shawnpg** [comment]
Hi. In theory, yes it can be used, though it has a not been tested yet AFAIK. If you can convert the headers and get FALCON and FALCON-Unzip to work, FALCON-Phase should have no trouble running.

Alternatively, if you assemble with Canu, you can then use purge_haplotigs (https://bitbucket.org/mroachawri/purge_haplotigs/src/master/) to separate the primary contigs from the alt haplotigs, and then adapt the assembly headers for FALCON-Phase (https://github.com/skingan/adapt_PurgeHaplotigs_for_FALCONPhase). That approach might also work with other assemblers -- it just hasn't been tested.

If you have some success with this, please post back so others in the community can see what you did! Also, please note that the most current, officially supported version of FALCON-Phase is within the PacBio Bioconda environment (https://github.com/PacificBiosciences/pbbioconda).

**Comment by yilunhuangyue** [comment]
Hi, I have tried to use nanopore data with Falcon/Falcon_unzip/Falcon_phase. I transformed the nanopore data to fit Falcon, but seems that the assembled contigs is of poor quality(contig N50 is less than 100Kb). Maybe It is not a good idea to use nanopore data with Falcon.
 Any way, thanks a lot for your advices.
