### ISSUE TITLE
replicates and cocktail restriction enzyme

### ISSUE THREAD

**Issue by olechnwin** [phasegenomics/FALCON-Phase#65]
Hi,

How do I run Falcon-phase with replicates HiC data?

**Comment by zeeev** [comment]
If they are technical replicates you can concatenate the fastq files. If they are different library preparations they cannot be mixed.

**Comment by olechnwin** [comment]
They are biological replicates. Does that mean I need to run falcon-phase separately for each replicates? I can't input the biological replicates as multiple samples in config.json? 

I have another question regarding enzyme. We are using Arima-HiC which uses a multiple 4-base cutting restriction enzymes with motifs GATC and GANTC. Can you please advice on the config.json, what motif should I put in? Can I put in both motifs separated by comma or something similar?

Thanks!

**Comment by zeeev** [comment]
Currently the code is setup for just one sample at a time.

For Arima data just list every motif the cutters will recognize. GA[A]TC,
GA[T]TC, GA[C]TC, GA[G]TC,CATC.

**Comment by olechnwin** [comment]
Thanks for your quick reply. 
Just to confirm the motifs should be listed like so in config.json?
"enzyme"		: "GATC,AGATCT,AAGCTT",

**Comment by zeeev** [comment]
Yes. However, if you're using Arima Hi-C you're missing a few motifs.
