### ISSUE TITLE
Error in rule nucmer

### ISSUE THREAD

**Issue by bd904** [phasegenomics/FALCON-Phase#66]
Hi, Here is the trackback of recent call. I don't know what is going wrong but i am unable to do phase separation.

```
[Mon Jun 24 12:00:45 2019]
Job 352: [info] aligning haplotigs to primary contigs with nucmer
/mnt/vol2/conda/miniconda3/envs/phase/bin/samtools faidx /mnt/vol2/projects/epidiverse/populus_nigra/PNI_NO_09_39_G1a_190122_C3_wgs/Alignments/Hi-C/Hap1/scaffold/scaffolds_FINAL.fasta 'scaffold_61' > 'test_data.scaffold_61.p.fa'
/mnt/vol2/conda/miniconda3/envs/phase/bin/samtools faidx /mnt/vol2/projects/epidiverse/populus_nigra/PNI_NO_09_39_G1a_190122_C3_wgs/Assembly/FC1094_cut150/supernova_outs/outs/FC1094_cut150.2.haplotigs.fasta 173:249-334511           > 'test_data.scaffold_61.h.fa'
/mnt/vol2/conda/miniconda3/envs/phase/bin/nucmer --maxmatch -l 100 -c 500 --delta='delta_files/test_data.scaffold_61.delta' -t 32 'test_data.scaffold_61.p.fa' 'test_data.scaffold_61.h.fa'
Full Traceback (most recent call last):
File "/mnt/vol2/conda/miniconda3/envs/phase/lib/python3.6/site-packages/snakemake/executors.py", line 1428, in run_wrapper
passed_shadow_dir)
File "/mnt/vol2/conda/miniconda3/envs/phase/bin/FALCON-Phase/pipeline/snakefile", line 491, in __rule_nucmer
File "/mnt/vol2/conda/miniconda3/envs/phase/lib/python3.6/site-packages/snakemake/shell.py", line 149, in __new__
raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source config.sh; set -eo pipefail ;  /mnt/vol2/conda/miniconda3/envs/phase/bin/samtools faidx /mnt/vol2/projects/epidiverse/populus_nigra/PNI_NO_09_39_G1a_190122_C3_wgs/Alignments/Hi-C/Hap1/scaffold/scaffolds_FINAL.fasta 'scaffold_11' > 'test_data.scaffold_11.p.fa'
/mnt/vol2/conda/miniconda3/envs/phase/bin/samtools faidx /mnt/vol2/projects/epidiverse/populus_nigra/PNI_NO_09_39_G1a_190122_C3_wgs/Assembly/FC1094_cut150/supernova_outs/outs/FC1094_cut150.2.haplotigs.fasta 33:1919-394028 33:439043-600878 33:609894-2723095 33:2805147-4479764 33:4524548-5287572 82:448-2576420 82:2634590-2904508 85:179-2164863 85:2203249-3311030           > 'test_data.scaffold_11.h.fa'
/mnt/vol2/conda/miniconda3/envs/phase/bin/nucmer --maxmatch -l 100 -c 500 --delta='delta_files/test_data.scaffold_11.delta' -t 32 'test_data.scaffold_11.p.fa' 'test_data.scaffold_11.h.fa'' returned non-zero exit status 1.

```

**Comment by shawnpg** [comment]
Hi,

It looks like a problem with samtools trying to get some info out of the assembly. Can you share the file scaffolds_FINAL.fasta so we can take a look? If it's a big file, send me a message and we'll get a share set up for you to upload it to, or we can download it if you already have it online somewhere.

Thanks for reporting this issue!

Shawn

**Comment by bd904** [comment]
scaffolds_FINAL.fasta
<https://drive.google.com/file/d/1SPROUJf-yS9CiCbuD6TsP3POlBEpf6RM/view?usp=drive_web>
Hi, Thanks for the response.
Here is the file!!

Thanks and Warm regards,
Bhumika Dubay
Contact:- bhumikadb427@gmail.com
                bd904@snu.edu.in
Phone number:-+393479838442

**Comment by shawnpg** [comment]
Thanks. I verified samtools faidx seems to work as expected on that file, so I suspect it's something to do with how samtools is configured to run in the condo environment. Can you try just running `samtools faidx` against that file in your environment and see if it is able to process it?

**Comment by bd904** [comment]
I tried but that works fine..
It generated the .fai file

Thanks and Warm regards,
Bhumika Dubay
Contact:- bhumikadb427@gmail.com
                bd904@snu.edu.in
Phone number:-+393479838442

**Comment by skingan** [comment]
It looks it might be an issue with the nucmer call. Can you run it in your shell and share the error message?

**Comment by bd904** [comment]
nucmer works as well..infact I tried running the test data and it produces expacted results.

**Comment by bd904** [comment]
Okay so I identified the error. Its with samtools and the error looks something like this:
`[faidx] Truncated sequence: 215:14542-4647735
[faidx] Truncated sequence: 233:5570-52350
[faidx] Truncated sequence: 125:179-1007509
[faidx] Truncated sequence: 217:216-193210
[faidx] Truncated sequence: 159:321-195664`

Now I don't know if it is because of the header name in the fasta files because I am trying to imply falcon on a merged assembly which is not coming from falcon-unzip.

**Comment by bd904** [comment]
Error detected.
The problem was in the haplotig file. it hasd some hiddne characteres which I removed using a simple command and the run was successful after this.

`sed 's/[!@#\$%^&*()]//g' filename`
