### ISSUE TITLE
parental k-mer counting 

### ISSUE THREAD

**Issue by erikenbody** [phasegenomics/FALCON-Phase#67]
Hi there,

Thanks for putting together this super useful software - it seems to be working well with my dataset. 

Now that I have both phased and unzip contigs, I'd like to produce a plot similar to figure 2a and 2d that shows k-mer counts for parental reads (which I have). Specifically I am referring to these methods:

> Parental k-mers were counted in the assemblies using the “simple-dump” utility from canu v 1.7. The proportion of “correct” parental k-mers was used as an overall measure of contig or scaffold phasing, and was plotted for each contig or scaffold in Figure 2.

As far as I can tell, simple-dump is deprecated in canu and I'm having trouble identifying the protocol used to count meryl produced k-mers in a non-canu assembly. Could you share any more details of the code (or point me to the raw code if I am missing it somewhere) you used to count parental k-mers in the unzip and falcon-phased assemblies? 

Thank you - any help is greatly appreciated!

**Comment by skingan** [comment]
Updated meryl info here: https://github.com/marbl/meryl/tree/master/scripts

Also useful but potentially out of date: https://github.com/arangrhie/TrioBinning

**Comment by erikenbody** [comment]
Thanks! The updated meryl page has precisely what I was looking for and had not been able to find.
