### ISSUE TITLE
Software producing identical haplotypes

### ISSUE THREAD

**Issue by bd904** [phasegenomics/FALCON-Phase#68]
I used falcon'phase on the 10X assembly converting all the data required in falcon unzip format.
The software runs fine with no error message but the two final output fasta files and the bed files it produced are identical. Do you have any idea what could be the problem?

**Comment by shawnpg** [comment]
Hi,

FALCON-Phase is intended for use with long-read-based assemblies and hasn't been tested with 10X data. It would be possible to convert the data to FALCON-Unzip format, but have the contigs and haplotigs themselves be insufficient for its algorithms to work. In particular, none of the output styles for Supernova are quite the same as what FALCON-Unzip does by default, so it would be important to reconfigure the Supernova assembly to have contigs and haplotigs that are the same kind of thing FALCON-Unzip produces. Specifically, the primary contigs would be pseudohap-style (style=3), and the haplotigs would be everything from megabubbles-style (style=2) that did not go into the primary contigs.

Thanks,

Shawn
