### ISSUE TITLE
haplotig header suffix.  Does the order matter?

### ISSUE THREAD

**Issue by Juke34** [phasegenomics/FALCON-Phase#72]
I need to convert headers modified by a third-party tool in a proper way to feed falcon-phase.
I was wondering if the suffix numbering in the haplotig header has an important meaning?

e.g my primary contig:
```
>000370F
```

my haplotigs 
```
>000370F_001
>000370F_002
>000370F_003
```

Does the order 001, 002, 003 reflects any order in the primary contig, like alignment order?
i.e must it be like that (case1):

```
primary  -------------------------------------------------------------------------

haoplotig   ---------------      -------------------        ------------------------
              001                           002                          003
```

or  it does not matter and can be any order like (case2):
```
primary   -------------------------------------------------------------------------

haoplotig   ---------------      -------------------        ------------------------
               003                           001                    002
```

**Comment by skingan** [comment]
The suffix on the haplotig name does not indicate order.
