### ISSUE TITLE
phased with falcon-unzip and falcon-phase

### ISSUE THREAD

**Issue by leeun357** [phasegenomics/FALCON-Phase#74]
hi,thank for create the good tool. but i have a question the how the relation of falcon-unzip and falcon-phased

**Comment by shawnpg** [comment]
Hi,

FALCON-Phase is used following FALCON-Unzip to correct phase switch errors using the Hi-C data. Documentation on the GitHub homepage (https://github.com/phasegenomics/FALCON-Phase) describes some of the usage, and the preprint (https://www.biorxiv.org/content/10.1101/327064v1) has more details on what it's doing. The full paper is in review as well and should be out shortly.

Thanks,

Shawn
