### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by alanorth** [phasegenomics/FALCON-Phase#76]
I'm installing FALCON-Phase for use on [our cluster](https://hpc.ilri.cgiar.org/) and I see there have been seventy commits to master since the v0.1.0-beta tag in 2018. Because there's no recent tag I guess I'll have to install it with version `git-7c50154e` or something. Can you please tag a new release to make this less ugly? Thanks. :)

**Comment by shawnpg** [comment]
Good point. Yes, we'll tag a new release once the open pull request (https://github.com/phasegenomics/FALCON-Phase/pull/78) for the other open issue is merged to master

**Comment by shawnpg** [comment]
Pull release integrated and a new release v0.2.0-beta https://github.com/phasegenomics/FALCON-Phase/releases/tag/v0.2.0-beta is now live. Thanks for the suggestions!
