### ISSUE TITLE
BioPython required for preprocess script

### ISSUE THREAD

**Issue by alanorth** [phasegenomics/FALCON-Phase#77]
It seems that BioPython is required for the `preprocess_diploid_asm_for_fc_phase.py` script, but it is not mentioned in the README:

```
$ python -V
Python 3.6.8
$ python bin/preprocess_diploid_asm_for_fc_phase.py
Traceback (most recent call last):
  File "bin/preprocess_diploid_asm_for_fc_phase.py", line 23, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'
```

Also, the script should have an executable bit like the other included Python scripts so that you can simply call it by name when it's in your PATH.

**Comment by shawnpg** [comment]
Good points! A pull request is coming with fixes for these shortly. https://github.com/phasegenomics/FALCON-Phase/pull/78

**Comment by maximilianpress** [comment]
PR fixing this is merged. Closing.
