### ISSUE TITLE
Mapping multiple Hi-C data

### ISSUE THREAD

**Issue by cgy0627** [phasegenomics/FALCON-Phase#79]
Hello,

I have five paired sets of Hi-C data that I would like to map to my contigs for scaffolding.
Should I combine the mapped bam files using tools like picard MergeSamFiles, or can I simply cat all the fastq files and map just once?

Thanks in advance.

**Comment by shawnpg** [comment]
Hi,

Either of these approaches should work, though cat'ing the FASTQ files together and aligning once is easiest and most common. It is important to cat the R1's and the R2's together in the same order so the reads stay paired in order in the resulting files. Here are some more recommendations around alignment: https://phasegenomics.github.io/2019/09/19/hic-alignment-and-qc.html

Thanks,

Shawn
