### ISSUE TITLE
libbz2 error on SGE cluster

### ISSUE THREAD

**Issue by skingan** [phasegenomics/FALCON-Phase#8]
dataset: full hummingbird
env: SGE cluster running CentOS6 ("pacbio bigmem")

### pipeline died at filtering BAM rule:

`Resources before job selection: {'_cores': 9223372036854775807, '_nodes': 20}
Ready jobs (1):
        bam_filt
Selected jobs (1):
        bam_filt
Resources after job selection: {'_cores': 9223372036854775806, '_nodes': 19}

Job 6: [info] filtering BAM

        /home/skingan/git/FALCON-Phase/bin/falcon-phase bamfilt -f 20 -m 10 -i hbird_VGP.unfiltered.bam -o hbird_VGP.filtered.bam
 
Submitted job 6 with external jobid 'Your job 28810 ("falcon-phase") has been submitted'.
Checking status of 1 jobs.
Checking status of 1 jobs.
Checking status of 1 jobs.
Error in rule bam_filt:
    jobid: 6
    output: hbird_VGP.filtered.bam
    cluster_jobid: Your job 28810 ("falcon-phase") has been submitted

Cleanup job metadata.
Releasing 1 _cores (now 9223372036854775807).
Releasing 1 _nodes (now 20).
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /pbi/dept/appslab/projects/2018/sbk_phaseUnzip/VGP/hbird/falcon_phase/.snakemake/log/2018-05-31T080551.538870.snakemake.log
unlocking
removing lock
removing lock
removed all locks
`

### qsub log:
`cat falcon-phase.e28810
[Thu May 31 08:06:05 2018] Building DAG of jobs...
[Thu May 31 08:06:05 2018] Using shell: /bin/bash
[Thu May 31 08:06:05 2018] Provided cores: 48
[Thu May 31 08:06:05 2018] Rules claiming more threads will be scaled down.
[Thu May 31 08:06:05 2018] Job counts:
[Thu May 31 08:06:05 2018]      count   jobs
[Thu May 31 08:06:05 2018]      1       bam_filt
[Thu May 31 08:06:05 2018]      1

[Thu May 31 08:06:05 2018] Job 0: [info] filtering BAM

[Thu May 31 08:06:05 2018]
[Thu May 31 08:06:05 2018]      /home/skingan/git/FALCON-Phase/bin/falcon-phase bamfilt -f 20 -m 10 -i hbird_VGP.unfiltered.bam -o hbird_VGP.filtered.bam
[Thu May 31 08:06:05 2018]
**/home/skingan/git/FALCON-Phase/bin/falcon-phase: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory**
[Thu May 31 08:06:06 2018] Error in rule bam_filt:
[Thu May 31 08:06:06 2018]     jobid: 0
[Thu May 31 08:06:06 2018]     output: hbird_VGP.filtered.bam

[Thu May 31 08:06:06 2018] RuleException:
[Thu May 31 08:06:06 2018] CalledProcessError in line 93 of /pbi/dept/appslab/projects/2018/sbk_phaseUnzip/VGP/hbird/falcon_phase/snakefile:
[Thu May 31 08:06:06 2018] Command ' source config.sh; set -eo pipefail ;
[Thu May 31 08:06:06 2018]      /home/skingan/git/FALCON-Phase/bin/falcon-phase bamfilt -f 20 -m 10 -i hbird_VGP.unfiltered.bam -o hbird_VGP.filtered.bam ' returned non-zero exit status 127.
[Thu May 31 08:06:06 2018]   File "/pbi/dept/appslab/projects/2018/sbk_phaseUnzip/VGP/hbird/falcon_phase/snakefile", line 93, in __rule_bam_filt
[Thu May 31 08:06:06 2018]   File "/mnt/software/p/python/3.6.4/lib/python3.6/concurrent/futures/thread.py", line 56, in run
[Thu May 31 08:06:06 2018] Shutting down, this might take some time.
[Thu May 31 08:06:06 2018] Exiting because a job execution failed. Look above for error message
[Thu May 31 08:06:06 2018] Complete log: /pbi/dept/appslab/projects/2018/sbk_phaseUnzip/VGP/hbird/falcon_phase/.snakemake/log/2018-05-31T080605.712916.snakemake.log
`

Currently determining how to load appropriate C libraries on system.

**Comment by zeeev** [comment]
Can you post the log file?

 /pbi/dept/appslab/projects/2018/sbk_phaseUnzip/VGP/hbird/falcon_phase/.snakemake/log/2018-05-31T080551.538870.snakemake.log

**Comment by skingan** [comment]
`cat /pbi/dept/appslab/projects/2018/sbk_phaseUnzip/VGP/hbird/falcon_phase/.snakemake/log/2018-05-31T080551.538870.snakemake.log
Building DAG of jobs...
Checking status of 0 jobs.
Using shell: /bin/bash
Provided cluster nodes: 20
Job counts:
        count   jobs
        1       bam_filt
        1       binmat
        1       dummy
        1       emit_haplotigs
        1       phase
        5
Resources before job selection: {'_cores': 9223372036854775807, '_nodes': 20}
Ready jobs (1):
        bam_filt
Selected jobs (1):
        bam_filt
Resources after job selection: {'_cores': 9223372036854775806, '_nodes': 19}

Job 6: [info] filtering BAM


        /home/skingan/git/FALCON-Phase/bin/falcon-phase bamfilt -f 20 -m 10 -i hbird_VGP.unfiltered.bam -o hbird_VGP.filtered.bam
     
Submitted job 6 with external jobid 'Your job 28810 ("falcon-phase") has been submitted'.
Checking status of 1 jobs.
Checking status of 1 jobs.
Checking status of 1 jobs.
Error in rule bam_filt:
    jobid: 6
    output: hbird_VGP.filtered.bam
    cluster_jobid: Your job 28810 ("falcon-phase") has been submitted

Cleanup job metadata.
Releasing 1 _cores (now 9223372036854775807).
Releasing 1 _nodes (now 20).
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /pbi/dept/appslab/projects/2018/sbk_phaseUnzip/VGP/hbird/falcon_phase/.snakemake/log/2018-05-31T080551.538870.snakemake.log
unlocking
removing lock
removing lock
removed all locks
`

**Comment by skingan** [comment]
The issue is that I compiled the binaries on Ubuntu but ran the pipeline on centos6. I will try compiling on the same OS.

**Comment by skingan** [comment]
Or i can run on Ubuntu. Which is what I will do.

**Comment by skingan** [comment]
I switched to an Ubuntu queue and the pipeline resumed.
