### ISSUE TITLE
Problem with phasing

### ISSUE THREAD

**Issue by cgy0627** [phasegenomics/FALCON-Phase#80]
Hello,

I have finished running FALCON-Phase on my data, but the fasta files in the output folder contains ID names such as:
" >000000F::000000F:0-61165_0
" >000000F::000000F_015_01:0-60186_0
" >000000F::000000F:125147-696346_0
" >000000F::000000F:0-61165_1
" >000000F::000000F:61165-125147_1
" >000000F::000000F:125147-696346_1

The manual says it should have names like:
" >000000F_0
" >000001F_0
" >000000F_1
" >000001F_1

Were the contigs supposed to merge in the last step? What could I do to solve this issue?

Thanks in advance.

**Comment by olechnwin** [comment]
Hi @cgy0627,

Did you figure out why the contig names like that? Are we supposed to merge them? Thanks!

**Comment by cgy0627** [comment]
Hi olechnwin,

When running bedtools getfasta, you have to change "-name" option to "-nameOnly". The former option prints out a combination of the first and fourth columns for gene IDs and that's why I had that error!

In short, in the FALCON-Phase/bin/emit_haplotigs.pl file you have to fix the lines 105-113:
```
my $cmd;
#unless (-s $phase0_tab_file) {
        $cmd = "$bedtools_path getfasta -tab **-nameOnly** -fi $unzip_asm_file -bed $bed0 > $tab0";
        system($cmd);
#}
#unless (-s $phase1_tab_file) {
        $cmd = "$bedtools_path getfasta -tab **-nameOnly** -fi $unzip_asm_file -bed $bed1 > $tab1";
        system($cmd);
#}
```

Hope this helps!

**Comment by olechnwin** [comment]
@cgy0627,

Thank you so much for sharing your fix. Really appreciate it!
